version: '3'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'finance'
      MONGO_INITDB_ROOT_PASSWORD: 'finance'
    ports:
    - "27017:27017"
    networks:
      - local



  app:
      depends_on:
       - mongo
      container_name: finance-api
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
      - ./:/home/app
      ports: 
      - "3131:3131"
      networks:
        - local

networks:
  local:
     name: local 
